homeassistant:
  name: Home

  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home

  unit_system: imperial
  time_zone: America/Chicago

  customize: !include_dir_merge_named customize

zone:
  name: Work
  latitude: !secret latitude_work
  longitude: !secret longitude_work

frontend:
config:
zeroconf:
conversation:
history:
logbook:

script: !include_dir_merge_named scripts
automation: !include_dir_merge_list automations
group: !include groups.yaml
sensor: !include_dir_merge_list sensors
device_tracker: !include_dir_merge_list device_trackers
switch: !include_dir_merge_list switches
camera: !include_dir_merge_list cameras
shell_command: !include shell_commands/shell_commands.yaml
input_slider: !include input/input_slider.yaml
input_boolean: !include input/input_boolean.yaml
input_select: !include input/input_select.yaml
rest_command: !include rest_commands/rest_commands.yaml

recorder:
  purge_days: 3

apcupsd:
  host: thor.vik
  port: 3551

updater:
  reporting: no

logger:
  default: warn

binary_sensor:
  - platform: workday
    country: US

zwave:
  usb_path: /dev/ttyUSB0
  config_path: /home/homeassistant/open-zwave/config

zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db

notify:
  - platform: pushbullet
    name: pushbullet
    api_key: !secret pushbullet_api_key
  - platform: telegram
    name: telegram
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_chat_id
  - platform: facebook
    name: facebook
    page_access_token: !secret facebook_page_access_token

weblink:
  entities:
    - name: "Grafana"
      url: 1.1.1.1
    - name: "Plex"
      url: 1.1.1.1
    - name: "Router"
      url: 1.1.1.1
    - name: "Odin (unRAID)"
      url: 1.1.1.1
    - name: "Pi-Hole Admin Page"
      url: 1.1.1.1
    - name: "HA Bridge"
      url: 1.1.1.1
    - name: "Odin (IPMI)"
      url: 1.1.1.1

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access
    aws_secret_access_key: !secret aws_secret
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

media_player:
  - platform: cast
    name: "Google Home"
    host: 1.1.1.1

http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  server_port: 8123
  server_host: !secret server_host_ip
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 3

telegram_bot:
  platform: webhooks
  api_key: !secret telegram_api_key
  trusted_networks:
    - 1.1.1.1
    - 149.154.167.197/32
    - 149.154.167.198/31
    - 149.154.167.200/29
    - 149.154.167.208/28
    - 149.154.167.224/29
    - 149.154.167.232/31
  allowed_chat_ids:
    - !secret telegram_chat_id

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

light:
  - platform: hue
    host: !secret hue_ip
    allow_unreachable: true
    name: "Hue Lights"

influxdb:
  host: !secret odin_host
  username: homeassistant
  password: homeassistant
  database: home_assistant
  include:
    entities:
       - sensor.broadlink_sensor_temperature
       - sensor.cpu_use
       - sensor.dark_sky_daily_high_temperature
       - sensor.dary_sky_daily_low_temperature
       - sensor.dark_sky_nearest_storm_distance
       - sensor.dark_sky_precip_intensity
       - sensor.dark_sky_precip_probability
       - sensor.dark_sky_temperature
       - sensor.pihole_ads_blocked_today
       - sensor.pihole_percentage_blocked_today
       - sensor.pihole_dns_queries_today
       - sensor.ram_use
       - sensor.ups_battery
       - sensor.ups_load
