- alias: "Bedtime"
  trigger:
    - platform: time
      after: "00:00:01"
  condition:
    condition: and
    conditions:    
      - condition: time 
        weekday: 
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: group.bedroom
        state: "on"
  action:
    - service: light.turn_on
      entity_id: light.bedroom_fan_light
      data:
        brightness: 50
        transition: 5
    - service: light.turn_off
      entity_id: light.bedroom_lamp_light
