- alias: "Button Push"
  trigger:
    platform: state
    entity_id: 
      - button.button1
      - button.button2
  action:
    service: notify.telegram
    data_template:
      message: " {{ trigger.to_state.attributes.friendly_name }} was pushed!"
