- alias: "Commute to Work"
  condition:
    condition: and
    conditions:
     - condition: time
       before: "09:00:00"
       after: "07:00:00"
     - condition: state
       entity_id: 'binary_sensor.workday_sensor'
       state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.phone_bt
    from: "home"
    to: "not_home"
  action:
    service: notify.telegram
    data_template:
      message: "It will take you {{ states.sensor.work_commute.state }} minutes to get to work"
