- alias: "Commute to Work"
  condition:
    condition: and
    conditions:
     - condition: time
       before: "08:00:00"
       after: "07:00:00"
     - condition: time
       weekday:
         - mon
         - tue
         - wed
         - thu
         - fri
  trigger:
    platform: state
    entity_id: device_tracker.phone_bt
    from: "home"
    to: "not_home"
  action:
    service: notify.pushbullet
    data_template:
      target: "device/phone"
      title: "Jarvis"
      message: "It will take you {{ states.sensor.work_commute.state }} minutes to get to work"
