- alias: "Sell BTC Trigger"
  initial_state: 'off'
  trigger:
    platform: template
    value_template: >
      {% if states('sensor.btc_wallet') and states('sensor.btc_thresh_val') %}
        {% if (states.sensor.btc_wallet.state > states.sensor.btc_thresh_val.state) %}
          true
        {% endif %}
      {% endif %}
  condition:
    condition: time
    before: '23:00:00'
    after: '08:00:00'
  action:
    - service: notify.telegram
      data_template:
        message: "Your BTC Wallet is currently at {{ states.sensor.btc_wallet.state }} USD"
    - service: automation.turn_off
      entity_id: automation.sell_btc_trigger
    - delay:
        minutes: 10
    - service: automation.turn_on
      entity_id: automation.sell_btc_trigger

- alias: "Sell ETH Trigger"
  initial_state: 'off'
  trigger:
    platform: template
    value_template: >
      {% if states('sensor.eth_wallet') and states('sensor.eth_thresh_val') %}
        {% if (states.sensor.eth_wallet.state > states.sensor.eth_thresh_val.state) %}
          true
        {% endif %}
      {% endif %}
  condition:
    condition: time
    before: '23:00:00'
    after: '08:00:00'
  action:
    - service: notify.telegram
      data_template:
        message: "Your ETH Wallet is currently at {{ states.sensor.eth_wallet.state }} USD"
    - service: automation.turn_off
      entity_id: automation.sell_eth_trigger
    - delay:
        minutes: 10
    - service: automation.turn_on
      entity_id: automation.sell_eth_trigger
