- alias: "Sell BTC Trigger"
  initial_state: 'off'
  trigger:
    platform: template
    value_template: "{% if (float(states.sensor.btc_wallet.state) > float(4000.00)) %}true{% endif %}"
  condition:
    condition: time
    before: '23:00:00'
    after: '08:00:00'
  action:
    - service: notify.pushbullet
      data_template:
        title: "Jarvis"
        target: "device/phone"
        message: "Your BTC Wallet is currently at {{ states.sensor.btc_wallet.state }} USD"
    - service: automation.turn_off
      entity_id: automation.sell_btc_trigger
    - delay:
        minutes: 10
    - service: automation.turn_on
      entity_id: automation.sell_btc_trigger

- alias: "Sell ETH Trigger"
  initial_state: 'off'
  trigger:
    platform: template
    value_template: "{% if (float(states.sensor.eth_wallet.state) > float(1200.00)) %}true{% endif %}"
  condition:
    condition: time
    before: '23:00:00'
    after: '08:00:00'
  action:
    - service: notify.pushbullet
      data_template:
        title: "Jarvis"
        target: "device/phone"
        message: "Your ETH Wallet is currently at {{ states.sensor.eth_wallet.state }} USD"
    - service: automation.turn_off
      entity_id: automation.sell_eth_trigger
    - delay:
        minutes: 10
    - service: automation.turn_on
      entity_id: automation.sell_eth_trigger
