- alias: "Device Status"
  initial_state: 'off'
  trigger:
    platform: state
    entity_id:
      - device_tracker.huehub
      - device_tracker.ir2ip
      - device_tracker.odin
      - device_tracker.router
  action:
    service: notify.telegram
    data_template:
      message: "{{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}"
