- alias: "HASS Startup Watchdog"
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.telegram
    data:
      message: "Home Assistant is online"
