- alias: "HASS Update Watchdog"
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.telegram
    data_template:
      message: "Home Assistant {{ states('updater.updater') }} is available." 
