- alias: "Home Intrusion Detection"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor_2_0
    from: "off"
    to: "on"
  condition:
    condition: state
    entity_id: group.me
    state: 'not_home'
    for:
      minutes: 5
  action:
    - delay: 00:05:00
    - service_template: >
        {% if is_state('group.me', 'not_home') %}notify.telegram{% endif %}
      data_template:
          message: "{% if is_state('group.me', 'not_home') %}WARNING: Motion has been detected{% endif %}"
