- alias: "Home Intrusion Detection"
  trigger:
    platform: state
    entity_id:
      - device_tracker.desktop
      - device_tracker.ir2ip
      - device_tracker.laptop
      - device_tracker.tv
      - light.bathroom_light_left
      - light.bathroom_light_middle
      - light.bathroom_light_right
      - light.bedroom_fan_light
      - light.bedroom_lamp_light
  condition:
    condition: state
    entity_id: device_tracker.phone_bt
    state: "not_home"
    for:
      minutes: 10
  action:
    service: notify.telegram
    data_template:
      message: "WARNING: {{ trigger.to_state.attributes.friendly_name }} has been turned {{ trigger.to_state.state }}"
