- alias: "Turn Lights Off When Not Home"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.me
    from: "home"
    to: "not_home"
  action:
    - delay:
        minutes: 5
    - service: light.turn_off
      data:
        entity_id: group.bedroom

- alias: "Turn Lights On When Home (Presence)"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.me
    to: "home"
    from: "not_home"
  action:
    service: light.turn_on
    data:
      entity_id: group.bedroom
      brightness: 254

- alias: "Turn Lights On When Home (Motion)"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor_2_0
    to: "on"
    from: "off"
  condition:
    condition: state
    entity_id: group.me
    state: "not_home"
  action:
    service: light.turn_on
    data:
      entity_id: group.bedroom
      brightness: 254

- alias: "Light Watchdog"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.bedroom
    to: "on"
    from: "off"
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: group.me
    state: "not_home"
  action:
    service: light.turn_off
    data:
      entity_id: group.bedroom
