- alias: "Precipitation Notification"
  initial_state: 'on'
  trigger:
    platform: template
    value_template: >
      {% if  is_state('sensor.home_weather_precip', 'unknown') and is_state('calendar.work', 'on') %} 
        false
      {% elif is_state('sensor.work_weather_precip', 'unknown') and is_state('calendar.work', 'off') %}
        false
      {% else %}
        true
      {% endif %}
  action:
    service: notify.telegram
    data_template:
      message: >
        {% if states.device_tracker.phone_gps %}
          It has started to {{ trigger.to_state.state }} at {{ states.device_tracker.phone_gps.state }}
        {% else %}
          It has started to rain
        {% endif %}
