- alias: "Rain Notification"
  trigger:
    platform: state
    entity_id: sensor.dark_sky_precip
    from: "unknown"
  action:
    service: notify.pushbullet
    data_template:
      title: "Jarvis"
      message: " {{ trigger.to_state.state }} has been detected in your area"
      target: "device/phone"
