- alias: "Smartwatch Watchdog"
  trigger:
    platform: state
    entity_id: device_tracker.phone_bt
    from: "home"
    to: "not_home"
    for:
      minutes: 1
  condition:
    condition: state
    entity_id: device_tracker.watch_bt
    state: "home"
    for:
      minutes: 5
  action:
    service: notify.telegram
    data:
      message: "You have left your watch at home"
