- alias: 'telegram ping pong'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    service: notify.telegram
    data:
      message: 'pong'

- alias: 'telegram restart'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/restart'
  action:
    - service: notify.telegram
      data:
        message: 'Restarting HA...'
    - service: shell_command.restart_hass

- alias: 'telegram fixtunnel'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/fixtunnel'
  action:
    - service: notify.telegram
      data:
        message: 'Fixing Dataplicity tunnel...'
    - service: shell_command.restart_dataplicty
    - service: notify.telegram
      data:
        message: 'Reset Dataplicity tunnel'

- alias: 'telegram location'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:  
      command: '/location'
  action:
    service: notify.telegram
    data_template:
      message: 'Last known location'
      data:
        location:
          latitude: '{{ float(states.device_tracker.phone_gps.attributes.latitude) }}'
          longitude: '{{ float(states.device_tracker.phone_gps.attributes.longitude) }}'

- alias: 'telegram weather'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/weather'
  action:
    service: notify.telegram
    data_template:
      message: >
        Today: {{ states.sensor.dark_sky_hourly_summary.state }}
         This week: {{ states.sensor.dark_sky_daily_summary.state }}

- alias: 'telegram start'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/start'
  action:
    service: notify.telegram
    data:
      message: 'Here is what I can do'
      data:
        keyboard:
          - '/ping, /location'
          - '/fixtunnel, /restart'
    


