- alias: 'telegram ping pong'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    service: notify.telegram
    data:
      message: 'pong'

- alias: 'telegram restart'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/restart'
  action:
    - service: notify.telegram
      data:
        message: 'Restarting HA...'
    - service: shell_command.restart_hass

- alias: 'telegram location'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:  
      command: '/location'
  action:
    service: notify.telegram
    data_template:
      message: 'Last known location'
      data:
        location:
          latitude: '{{ float(states.device_tracker.phone_gps.attributes.latitude) }}'
          longitude: '{{ float(states.device_tracker.phone_gps.attributes.longitude) }}'

- alias: 'telegram weather'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/weather'
  action:
    service: notify.telegram
    data_template:
      message: >
        Currently: {{ states.sensor.home_weather_minutely_summary.state|replace(".", "") }} in Denton and
        {% if states.sensor.home_weather_minutely_summary.state|replace(".","") == states.sensor.work_weather_minutely_summary.state|replace(".","") -%}
         Westlake.
        {% else -%}
        {{ states.sensor.work_weather_minutely_summary.state|replace(".", "")|lower }} in Westlake.
        {% endif %}
        {{- '\n' -}}
        24 hours: {{ states.sensor.home_weather_hourly_summary.state|replace(".", "") }} in Denton and
        {% if states.sensor.home_weather_hourly_summary.state|replace(".","") == states.sensor.work_weather_hourly_summary.state|replace(".","") -%}
         Westlake.
        {% else -%}
        and {{ states.sensor.work_weather_hourly_summary.state|replace(".", "")|lower }} in Westlake.
        {% endif %}

- alias: 'telegram start'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/start'
  action:
    service: notify.telegram
    data:
      message: 'Here is what I can do'
      data:
        keyboard:
          - '/ping, /location, /weather'
          - '/restart'
