- alias: "Traffic Watchdog"
  initial_state: 'off'
  trigger:
    platform: template
    value_template: "{% if as_timestamp(now()) >= ((as_timestamp(states.calendar.work.attributes.start_time) -states.sensor.work_commute.state|float *60)|timestamp_custom('%')) %}true{% else %}false{% endif %}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.me
        state: 'home'
      - condition: and
        conditions:
        - condition: time
          before: '09:00:00'
          after: '07:00:00'
        - condition: state
          entity_id: 'binary_sensor.workday_sensor'
          state: 'on'
  action:
    service: notify.telegram
    data:
      message: "You are going to be late for work!"
