- alias: "Wake Computer When Home"
  initial_state: 'off'
  condition:
    condition: and
    conditions:
      - condition: time
        before: "23:00:00"
        after: "17:00:00"
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
  trigger:
    platform: state
    entity_id: group.me
    to: "home"
  action:
    service: homeassistant.turn_on
    entity_id: switch.desktop_wol
