- alias: "Wake Computer When Home"
  initial_state: 'off'
  condition:
    condition: and
    conditions:
      - condition: time
        before: "23:00:00"
        after: "17:00:00"
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  trigger:
    platform: state
    entity_id: device_tracker.phone_bt
    to: "home"
  action:
    service: homeassistant.turn_on
    entity_id: switch.desktop_wol
